name: Continuous Integration / Delivery

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_pull_request_actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      - name: Deploy 🚀 
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build